influxdb_leader_ip: "{{ hostvars[groups['influxdb'][0]]['private_ip'] }}"

influxdb_retention_policies:
  - name: rp_7d
    duration: 7d
    replication: 2
    default: true
  - name: rp_60d
    duration: 60d
    replication: 2
  - name: rp_52w
    duration: 52w
    replication: 2

influxdb_measurements_to_downsample:
  - cpu_busy
  - cpu_guest
  - cpu_guestNice
  - cpu_idle
  - cpu_iowait
  - cpu_irq
  - cpu_nice
  - cpu_percentageBusy
  - cpu_percentageGuest
  - cpu_percentageGuestNice
  - cpu_percentageIdle
  - cpu_percentageIowait
  - cpu_percentageIrq
  - cpu_percentageNice
  - cpu_percentageSoftirq
  - cpu_percentageSteal
  - cpu_percentageStolen
  - cpu_percentageSystem
  - cpu_percentageUser
  - cpu_softirq
  - cpu_steal
  - cpu_stolen
  - cpu_system
  - cpu_user
  - disk_free
  - disk_inodes_free
  - disk_inodes_total
  - disk_inodes_used
  - disk_total
  - disk_used
  - io_io_time
  - io_read_bytes
  - io_read_time
  - io_reads
  - io_write_bytes
  - io_write_time
  - io_writes
  - mem_active
  - mem_available
  - mem_buffers
  - mem_cached
  - mem_free
  - mem_inactive
  - mem_shared
  - mem_total
  - mem_used
  - mem_used_perc
  - mem_wired
  - net_bytes_recv
  - net_bytes_sent
  - net_drop_in
  - net_drop_out
  - net_err_in
  - net_err_out
  - net_packets_recv
  - net_packets_sent
  - swap_free
  - swap_in
  - swap_out
  - swap_total
  - swap_used
  - swap_used_perc
  - system_load1
  - system_load15
  - system_load5
  - system_uptime
  - system_uptime_format
